const express = require('express');
const router = express.Router();
const authorize=require('../middlewares/AuthorizeAdmin.js');
const adminController = require('../controllers/AdminController.js');
router.use(authorize);
router.get('/Users',adminController.getUsers);
router.delete('/ban/user',adminController.BanUser);
router.post('/ban/user',adminController.unBanUser);
router.get('/ban/user',adminController.getBannedUsers);
router.delete('/ban/art',adminController.BanArt);
router.post('/ban/art',adminController.unBanArt);
router.get('/ban/art',adminController.getBannedArts);
router.post('/exhibition',adminController.startExhibition);
router.delete('/exhibition',adminController.endExhibition);
router.put('/exhibition',adminController.updateExhibition);
router.post('/exhibition/arts',adminController.addArtToExhibition);
router.delete('/exhibition/arts',adminController.removeArtFromExhibition);
router.put('/auction/approve',adminController.approveAuction);
router.put('/auction/reject',adminController.rejectAuction);
router.delete('/auction',adminController.deleteAuction);
module.exports = router;